#! /bin/bash
clear
echo " "
echo " 1) Abra mais três telas de terminal, 3x CTRL + SHIFT + T "
echo " "
echo " 2) No segundo terminal, para CONSTRUIR os conteiners de PostgreSQL e PGAdmin, "
echo " "
echo " sudo docker-compose up"
echo " "
echo " 3) No terceiro termina, verifique se os conteineres de banco de dados estão Up (em execução)."
echo " "
echo " sudo docker ps -a | grep f2-modulo1-curso1-projeto-go-testes"
echo " "
echo " Algo semelhando ao que é mostrado na tela abaixo:"
echo " "
echo " CONTAINER ID   IMAGE             STATUS                    PORTS                                              NAMES                                                 "
echo " 7670b0521ce0   dpage/pgadmin4    Up 2 minutes              443/tcp, 0.0.0.0:54321->80/tcp, :::54321->80/tcp   f2-modulo1-curso1-projeto-go-testes-pgadmin-compose-1 "
echo " 8c817e0a8ed2   postgres          Up 2 minutes              0.0.0.0:5432->5432/tcp, :::5432->5432/tcp          f2-modulo1-curso1-projeto-go-testes-postgres-1        "
echo " "
echo " Se os dois conteineres estiverem 'Up' então executo o comando para rodar a aplicação GO."
echo " " 
echo " 3) No terceiro termina, para executar a aplicação..."
echo " "
echo " go run main.go"
echo " "
echo " 4) para testar a infraestrutura e a aplicação:"
echo " " 
echo " PGAdmin - Gerenciador do PostGreSQL"
echo " " 
echo " No browser da máquina host digite:  http://0.0.0.0:54321"
echo " "
echo "    Login e-mail: gui@alura.com "
echo "    Senha       : 123456        "
echo " "
echo " Para testar a aplicação: No browser da máquina host digite: http://0.0.0.0:8080/Bruno"
echo " "

