#! /bin/bash
clear
echo " "
echo " Passo a passo para iniciar (START) em todo ambinte da aplicação teste GO usada no curso Formação 2 - Módulo 1 - Curso 1."
echo " " 
echo " Para Iniciar os conteineres de banco de dados PostgreSql e PGAdmin..."
echo " "
echo " 1) No segundo terminal digite: "
echo " "
echo "     sudo docker start f2-modulo1-curso1-projeto-go-testes-pgadmin-compose-1"
echo " "
echo " No segundo terminal digite: "
echo " " 
echo "    sudo docker start f2-modulo1-curso1-projeto-go-testes-postgres-1"
echo " "
echo " 2) No segundo terminal, teste se os conteineres de banco de dados estão rodando. Eles deven estar com status (Up):"
echo " "
echo "     sudo docker ps -a | grep f2-modulo1-curso1-projeto-go-testes"
echo " " 
echo " 3) No terceiro terminal, para iniciar a aplicação em um outro terminal digite: "
echo " "
echo "     go run main.go"
echo " " 
echo " 3) No quarto terminal, verifique o status geral do ambiente da aplicação de teste GO."
echo " "
echo "     ./ver-ambiente.sh"
echo " "
echo " Se precisar recontruir novamente toda a infraestrutura e a aplicação, no terminal 1/4 execute: ( ./executar-aplicação.sh ) e siga o passo a passo novamente. "
echo " "
